name:                hpaie
version:             0.1.0.0
github:              "githubuser/hpaie"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hpaie#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- directory
- filepath
- parsec
- prettyprinter
- process
- regex-tdfa
- regex-tdfa-text
- text
- time
- vector

default-extensions:
- OverloadedStrings
- DeriveGeneric

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fno-warn-orphans

executables:
  gen-ledger:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpaie

  assign-keys:
    main:                Main.hs
    source-dirs:         assign
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpaie

tests:
  hpaie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpaie
    - hspec
    - hspec-discover
    - HUnit
    - text
    - time
